spring.application.name=aplication
spring.profiles.active=test
spring.jpa.open-in-view=true
server.port=8081
spring.config.import=optional:file:.env[.properties]

# Regras de negocio para anexo de imagem

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=4MB

cloudinary.url=${CLOUDINARY_URL}

app.security.jwt.secret=${secretToken}
app.security.jwt.expiration-minutes=60

app.security.password-reset.expiration-minutes=15