package Lokei.aplication.infrastructure.persistence.enums;

public enum categoriaEnum {
    ALICATES,
    APARADORES_E_CORTADORES_DE_GRAMA,
    BETONEIRAS,
    CAIXAS_E_MALETAS_DE_FERRAMENTAS,
    CHAVES_DE_FENDA,
    EQUIPAMENTOS_DE_PROTECAO_INDIVIDUAL,
    ESCADAS,
    ESMILHADEIRAS,
    ESQUADROS_FITAS_METRICAS_E_TRENAS,
    FURADEIRAS_E_PARAFUSADEIRAS,
    LIXADEIRAS,
    MARTELOS,
    SERRAS_E_MOTOSSERRAS,
    OUTROS
}
