package Lokei.aplication.domain.enums;

public enum tipoNotificacaoEnum {
    RESERVA_SOLICITADA,
    RESERVA_APROVADA,
    RESERVA_REPROVADA,
    RESERVA_CANCELADA,
    NOVA_MENSAGEM,
    DENUNCIA_CRIADA,
    DENUNCIA_MODERADA,
    ALTERACAO_EMAIL,
    RECUPERACAO_SENHA
}

