create table enderecos (
    id integer generated by default as identity primary key,
    logradouro varchar(255) not null,
    bairro varchar(255) not null,
    numero varchar(255) not null,
    complemento varchar(255),
    cidade varchar(255) not null,
    estado varchar(2) not null,
    cep varchar(8) not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null
);

create table usuarios (
    id integer generated by default as identity primary key,
    nome varchar(255) not null,
    email varchar(255) not null,
    cpf varchar(11) not null,
    telefone varchar(11) not null,
    senha_hash varchar(255) not null,
    papel varchar(50) not null,
    termos_aceitos boolean not null,
    cpf_validado boolean not null,
    ativo boolean not null,
    email_verificado boolean not null,
    email_pendente varchar(255),
    endereco_id integer,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint uk_usuario_email unique (email),
    constraint uk_usuario_cpf unique (cpf),
    constraint fk_usuario_endereco foreign key (endereco_id) references enderecos(id)
);

create table anuncios (
    id integer generated by default as identity primary key,
    titulo varchar(255) not null,
    descricao text not null,
    valor_diario numeric(12,2) not null,
    status varchar(50) not null,
    categoria varchar(100) not null,
    proprietario_id integer not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint fk_anuncio_proprietario foreign key (proprietario_id) references usuarios(id)
);

create table imagens (
    id integer generated by default as identity primary key,
    nome_arquivo varchar(255) not null,
    imagem_url varchar(255) not null,
    content_type varchar(100) not null,
    tamanho_bytes bigint not null,
    ordem integer not null,
    anuncio_id integer,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint fk_imagem_anuncio foreign key (anuncio_id) references anuncios(id)
);

create table alugueis (
    id integer generated by default as identity primary key,
    data_inicio date not null,
    data_fim date not null,
    valor_total numeric(12,2) not null,
    status_aluguel varchar(50) not null,
    data_aprovacao timestamp,
    data_cancelamento timestamp,
    motivo_reprovacao text,
    motivo_cancelamento text,
    anuncio_id integer not null,
    locatario_id integer not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint fk_aluguel_anuncio foreign key (anuncio_id) references anuncios(id),
    constraint fk_aluguel_locatario foreign key (locatario_id) references usuarios(id)
);

create table conversas_chat (
    id integer generated by default as identity primary key,
    aluguel_id integer not null,
    locador_id integer not null,
    locatario_id integer not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint uk_conversa_aluguel unique (aluguel_id),
    constraint fk_conversa_aluguel foreign key (aluguel_id) references alugueis(id),
    constraint fk_conversa_locador foreign key (locador_id) references usuarios(id),
    constraint fk_conversa_locatario foreign key (locatario_id) references usuarios(id)
);

create table mensagens_chat (
    id integer generated by default as identity primary key,
    conteudo text not null,
    conversa_id integer not null,
    remetente_id integer not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint fk_mensagem_conversa foreign key (conversa_id) references conversas_chat(id),
    constraint fk_mensagem_remetente foreign key (remetente_id) references usuarios(id)
);

create table avaliacoes (
    id integer generated by default as identity primary key,
    nota integer not null,
    comentario text not null,
    tipo varchar(50) not null,
    aluguel_id integer not null,
    autor_id integer not null,
    alvo_usuario_id integer,
    anuncio_id integer,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint fk_avaliacao_aluguel foreign key (aluguel_id) references alugueis(id),
    constraint fk_avaliacao_autor foreign key (autor_id) references usuarios(id),
    constraint fk_avaliacao_alvo_usuario foreign key (alvo_usuario_id) references usuarios(id),
    constraint fk_avaliacao_anuncio foreign key (anuncio_id) references anuncios(id)
);

create table denuncias (
    id integer generated by default as identity primary key,
    motivo varchar(100) not null,
    descricao text not null,
    status varchar(50) not null,
    data_decisao timestamp,
    parecer_administrativo text,
    anuncio_id integer not null,
    denunciante_id integer not null,
    administrador_id integer,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint fk_denuncia_anuncio foreign key (anuncio_id) references anuncios(id),
    constraint fk_denuncia_denunciante foreign key (denunciante_id) references usuarios(id),
    constraint fk_denuncia_admin foreign key (administrador_id) references usuarios(id)
);

create table denuncia_imagens (
    denuncia_id integer not null,
    imagem_url varchar(255) not null,
    constraint fk_denuncia_imagem foreign key (denuncia_id) references denuncias(id)
);

create table notificacoes (
    id integer generated by default as identity primary key,
    tipo varchar(50) not null,
    titulo varchar(255) not null,
    mensagem text not null,
    lida boolean not null,
    usuario_id integer not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint fk_notificacao_usuario foreign key (usuario_id) references usuarios(id)
);

create table tokens_recuperacao_senha (
    id integer generated by default as identity primary key,
    token varchar(255) not null,
    expiracao timestamp not null,
    usado boolean not null,
    usuario_id integer not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint uk_token_recuperacao unique (token),
    constraint fk_token_recuperacao_usuario foreign key (usuario_id) references usuarios(id)
);

create table tokens_verificacao_email (
    id integer generated by default as identity primary key,
    token varchar(255) not null,
    novo_email varchar(255) not null,
    expiracao timestamp not null,
    usado boolean not null,
    usuario_id integer not null,
    data_criacao timestamp not null,
    data_atualizacao timestamp not null,
    constraint uk_token_verificacao_email unique (token),
    constraint fk_token_verificacao_usuario foreign key (usuario_id) references usuarios(id)
);

create index idx_anuncio_status on anuncios(status);
create index idx_anuncio_categoria on anuncios(categoria);
create index idx_aluguel_status on alugueis(status_aluguel);
create index idx_aluguel_periodo on alugueis(anuncio_id, data_inicio, data_fim);
create index idx_avaliacao_anuncio_tipo on avaliacoes(anuncio_id, tipo);
create index idx_avaliacao_usuario_tipo on avaliacoes(alvo_usuario_id, tipo);
create index idx_denuncia_status on denuncias(status);
create index idx_notificacao_usuario on notificacoes(usuario_id);
